language: cpp
compiler:
- g++-4.8
sudo: true
cache:
  directories:
  - lib/sbpl/build
  - /usr/lib/ccache
  - lib/cpprestsdk/Release/tests
  - lib/cpprestsdk/Release/tests/CMakeFiles
  - lib/cpprestsdk/Release/samples
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libssl-dev
    - astyle
    - g++-4.8
install:
- export CXX="g++-4.8"
- make
script: make
before_install:
- echo $LANG
- echo $LC_ALL
- sudo add-apt-repository ppa:boost-latest/ppa -y
- sudo apt-get update
- sudo apt-get install libboost-chrono1.55-dev libboost-random1.55-dev libboost-system1.55-dev libboost-filesystem1.55 libboost-thread1.55 libboost-regex1.55
- ls /usr/lib | grep boost || echo "empty"
- cd lib/sbpl
- mkdir -p build
- cd build
- cmake ..
- make
- sudo make install
- cd ../../cpprestsdk/Release
- mkdir -p build.release
- cd build.release
- CXX=g++-4.8 cmake .. -DCMAKE_BUILD_TYPE=Release
- make -j 2
- sudo make install
- cd ../../../../
notifications:
  irc:
    channels:
    - "chat.freenode.net#cnuuaslab"
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  slack: "suas:oeGJ8juXQ75A5cBqj51vLRBB"
env:
  global:
  - LANG="en_US.UTF-8"